### ISSUE TITLE
skins, heads, world on replit

### ISSUE THREAD

**Issue by William60081011** [WorldEditAxe/eaglerxbungee-reimpl#4]
skins of players, citizens arent showing right
and for player heads the same
and when u tp to another world u gotta wait for 2/3 fps drops before u can do anything
on replit proxy
also whats ur discord

**Comment by WorldEditAxe** [comment]
1 & 2. Are you using the latest release? The latest release has these issues fixed.
3. This FPS drop issue isn't something we can fix, as it's an issue originating from the game client itself.

**Comment by William60081011** [comment]
Whts thelatest release bc i only kniw tht eagler 1.8 released and i downloaded tht client

**Comment by WorldEditAxe** [comment]
https://github.com/WorldEditAxe/eaglerxbungee-reimpl/releases/tag/v1.0.0
If you're using the fork of the Eaglercraft proxy on Repl.it, replace everything in the `proxy` folder with the files in the .zip download.

**Comment by William60081011** [comment]
why wont you update ur original replit respitority, so no one has any issues

**Comment by William60081011** [comment]
it worked btw and pls tell me ur discord
