### ISSUE TITLE
End of stream

### ISSUE THREAD

**Issue by vhcrack** [WorldEditAxe/eaglerxbungee-reimpl#5]
Whenever I connect to the offline server I have with the proxy, it says "end of stream".
Here are a two _hypothetical reasons_ why I think it's happening:
- Server that connection is being made to is a **Bungeecord** server.
- Fallback servers are not 1.8.9; ViaVersion is not compatible with Eagler/this proxy software, resulting in the "End of stream" error.

No errors are sent to any of the consoles.

**Comment by WorldEditAxe** [comment]
As far as I know, you only get this vague error when the proxy to server connection is terminated during the login stage. Are you sure the BungeeCord server allows offline players?

**Comment by vhcrack** [comment]
> As far as I know, you only get this vague error when the proxy to server connection is terminated during the login stage. Are you sure the BungeeCord server allows offline players? Is something on the BungeeCord server itself blocking the connection?

Bungeecord is in offline mode alongside all other backend servers. I'm stumped as to what could be preventing the connection.

**Comment by WorldEditAxe** [comment]
Have you checked your firewall for issues that may be preventing communication? I was able to join some cracked Minecraft server networks perfectly fine, which probably hints towards either a firewall or a BungeeCord configuration issue. Try connecting to the server's public IP with the proxy set up on your computer.

**Comment by vhcrack** [comment]
> Have you checked your firewall for issues that may be preventing communication? I was able to join some cracked Minecraft server networks perfectly fine, which probably hints towards either a firewall or a BungeeCord configuration issue. Try connecting to the server's public IP with the proxy set up on your computer.

Sent my config so you could look at it. I tried connecting with a proxy on my own computer and it did the same thing.
Also, when I turned on **proxy-protocol** in the config, it did let me log in but it said something like `[/ipaddresshere] <-> InitialHandler - read timed out.`.

**Comment by vhcrack** [comment]
As for the firewall thing, what do you think I could do to fix that? I'm currently hosting my server on a [3rd party host](https://sparkedhost.com/). Are there specific ports I may have to open?

**Comment by WorldEditAxe** [comment]
Your issue is probably not firewall related, given that you were able to connect outside of the server network. Does anything happen when you disable `proxy-protocol`? Does your server implement any anti-bot plugins? (the proxy uses `node-minecraft-protocol` to complete the initial handshake)

**Comment by vhcrack** [comment]
> Your issue is probably not firewall related, given that the same issue occurred outside of the server network. Does anything happen when you disable `proxy-protocol`? Does your server implement any anti-bot plugins? (the proxy uses `node-minecraft-protocol` to complete the initial handshake with the remote server)

When I disable proxy-protocol it just kicks me out with an End of stream error immediately instead of logging in for an extended amount of time. As for any anti-bot plugins, I'll have to get back to you in about an hour as I'm busy. I'll reply once I check.

**Comment by WorldEditAxe** [comment]
This probably hints towards someone preventing the client from connecting to the server. I'll add some code to log kick messages to console, so we can get to the root of the issue.

**Comment by vhcrack** [comment]
> This probably hints towards someone preventing the client from connecting to the server. I'll add some code to log kick messages to console, so we can get to the root of the issue.

So uh, quick update, it works now.
Have literally no idea why but it just does.
Thanks for the support thus far LMFAO
![image](https://user-images.githubusercontent.com/26697033/209455508-9c7466a3-475b-46d7-a027-66923da7c8c3.png)

**Comment by vhcrack** [comment]
> > This probably hints towards someone preventing the client from connecting to the server. I'll add some code to log kick messages to console, so we can get to the root of the issue.
> 
> So uh, quick update, it works now. Have literally no idea why but it just does. Thanks for the support thus far LMFAO ![image](https://user-images.githubusercontent.com/26697033/209455508-9c7466a3-475b-46d7-a027-66923da7c8c3.png)

Doesn't work on replit for some reason, but works when I host locally. Odd...

**Comment by WorldEditAxe** [comment]
You may have some anti VPN proxy or software preventing the Repl.it client from connecting. This is to be expected, however, given that Repl.it runs on Google's GCP, which could be flagged as being a proxy. Although I'd suggest entering the proxy's IP into the IP whitelist, repl IPs are dynamic, so there's no real way to whitelist them.
If possible, contact your hosting provider to see if you can run the proxy on your BungeeCord server and open the TCP port 80/443 (for connectivity purposes).

**Comment by vhcrack** [comment]
> You may have some anti VPN/proxy plugin or software preventing the Repl.it client from connecting. This is to be expected, however, given that Repl.it runs on Google's GCP, which could be flagged. Although I'd suggest entering the proxy's IP into the IP whitelist, repl IPs are dynamic, so there's no real way to whitelist them.
> If possible, contact your hosting provider to see if you can run the proxy on your BungeeCord server and open the TCP port 80/443 (for connectivity purposes).

This is what they said to me:
"You would need to run this on a bot hosting plan as it's NodeJS, you won't be able to get 80/443 but we offer a free reverse proxy in the panel where you can use your own domain. It looks like you can just change the port in the config."
"If you need to use a domain I guess, I'd confirm if 80/443 is required or just recommended"

**Comment by vhcrack** [comment]
I'm going to try and host this on Glitch.com and see what happens.

**Comment by vhcrack** [comment]
Works now on repl, how odd. Gonna close this issue, will reopen if anything happens.

**Comment by vhcrack** [comment]
That didn't last long.

```
W 2022-12-25T06:39:31.647Z PacketHandler: Error occurred whilst handling handshake! Error: TypeError: wasm function signature contains illegal type
    at file:///home/container/node_modules/@thi.ng/leb128/index.js:24:27
    at doHandshake (file:///home/container/utils.js:160:21)
    at handlePacket (file:///home/container/listener.js:15:13)
    at WebSocket.<anonymous> (file:///home/container/index.js:58:9)
    at WebSocket.emit (events.js:400:28)
    at Receiver.receiverOnMessage (/home/container/node_modules/ws/lib/websocket.js:1178:20)
    at Receiver.emit (events.js:400:28)
    at Receiver.dataMessage (/home/container/node_modules/ws/lib/receiver.js:513:14)
    at Receiver.getData (/home/container/node_modules/ws/lib/receiver.js:446:17)
    at Receiver.startLoop (/home/container/node_modules/ws/lib/receiver.js:148:22)
```

**Comment by WorldEditAxe** [comment]
Can you try Node.js 16?

**Comment by vhcrack** [comment]
> Can you try Node.js 16?

End of stream error

**Comment by vhcrack** [comment]
Nevermind, seems like it's just an issue with the web.arch.lol of EaglerCraftX you have listed lol. Gonna create a new issue/reopen if anything comes up.
